name: Express.js CI #nombre Continuos Integration Express.js
on:
  push: # correr push en rama main
    branches: [ main ] 
  pull_request: # correr pull_request en rama main
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: Prueba2
          
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            - 5432:5432
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: "16.15"

    - name: Installing Dependencies # Instalar dependencias
      run: npm i

    - name: Run tests # correr test
      run: npm test